# Generated by Django 4.2 on 2025-01-06 20:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("lat", models.CharField(max_length=1000)),
                ("lon", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpotSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="spots.spot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SnapshotAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "wave_size_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="\n        Try to assess wave size where:\n            FLAT = 0\n            KNEES = 1\n            HIP = 2\n            CHEST = 3\n            HEAD = 4\n            OVERHEAD = 5\n            HEAD_AND_HALF = 6\n            DOUBLE_SHOULDER = 7\n            DOUBLE_OVERHEAD = 8\n    ",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("8.0")),
                        ],
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="spots.spotsnapshot",
                    ),
                ),
            ],
        ),
    ]
