# Generated by Django 4.2 on 2024-09-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meteonetwork", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "wave_type_score",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("lat", models.CharField(max_length=1000)),
                ("lon", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("windy_webcam_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SpotSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "meteonetwork_irt_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="meteonetwork.meteonetworkirtdata",
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="spots.spot"
                    ),
                ),
            ],
        ),
    ]
