# Generated by Django 4.2 on 2025-01-16 21:38

from uuid import uuid4

from django.db import migrations, models


def backfill_spot_uids(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Spot = apps.get_model("spots", "Spot")
    spots = list(Spot.objects.all())
    for spot in spots:
        spot.uid = uuid4()
    return Spot.objects.bulk_update(spots, ["uid"])


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="uid",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.RunPython(backfill_spot_uids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="spot",
            name="uid",
            field=models.UUIDField(unique=True),
        ),
    ]
