# Generated by Django 4.2 on 2024-09-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spots", "0001_initial"),
        ("windy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotsnapshot",
            name="windy_webcam_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="windy.windywebcamdata"
            ),
        ),
        migrations.AddField(
            model_name="snapshotassessment",
            name="snapshot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="spots.spotsnapshot"
            ),
        ),
    ]
