# Generated by Django 4.2 on 2024-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spot",
            name="cft_buoy_station_id",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
