# Generated by Django 4.2 on 2025-02-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0002_spot_uid"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapshotDiscarded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discarded",
                        to="spots.spotsnapshot",
                    ),
                ),
            ],
        ),
    ]
