# Generated by Django 4.2 on 2025-01-02 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0004_spotsnapshot_cft_buoy_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spot",
            name="cft_buoy_station_id",
        ),
        migrations.RemoveField(
            model_name="spot",
            name="windy_webcam_id",
        ),
    ]
