# Generated by Django 4.2 on 2025-01-02 21:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0005_remove_spot_cft_buoy_station_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshotassessment",
            name="wave_type_score",
        ),
        migrations.AddField(
            model_name="snapshotassessment",
            name="wave_size_score",
            field=models.DecimalField(
                decimal_places=4,
                default=None,
                help_text="\n        Try to assess surfability where:\n            FLAT = 0\n            LESSON = 1\n            LONGBOARD = 2\n            SHORTBOARD = 3\n    ",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("3.0")),
                ],
            ),
            preserve_default=False,
        ),
    ]
