# Generated by Django 4.2 on 2025-01-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0006_remove_snapshotassessment_wave_type_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotsnapshot",
            name="cft_buoy_data",
        ),
        migrations.RemoveField(
            model_name="spotsnapshot",
            name="meteonetwork_irt_data",
        ),
        migrations.RemoveField(
            model_name="spotsnapshot",
            name="windy_webcam_data",
        ),
        migrations.AlterField(
            model_name="spot",
            name="name",
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
