# Generated by Django 4.2 on 2025-01-05 16:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0007_remove_spotsnapshot_cft_buoy_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshotassessment",
            name="wave_size_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="\n        Try to assess wave size where:\n            FLAT = 0\n            KNEES = 1\n            HIP = 2\n            CHEST = 3\n            HEAD = 4\n            OVERHEAD = 5\n            HEAD_AND_HALF = 6\n            DOUBLE_SHOULDER = 7\n            DOUBLE_OVERHEAD = 8\n    ",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("8.0")),
                ],
            ),
        ),
    ]
