# Generated by Django 4.2 on 2025-01-05 16:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0008_alter_snapshotassessment_wave_size_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshotassessment",
            name="surf_quality_score",
            field=models.DecimalField(
                decimal_places=4,
                default=None,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("6.0")),
                ],
            ),
            preserve_default=False,
        ),
    ]
