# Generated by Django 4.2 on 2025-01-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0007_remove_spotsnapshot_cft_buoy_data_and_more"),
        ("meteonetwork", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meteonetworkirtdata",
            name="spot",
        ),
        migrations.AddField(
            model_name="meteonetworkirtdata",
            name="snapshot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="spots.spotsnapshot",
            ),
            preserve_default=False,
        ),
    ]
