# Generated by Django 4.2 on 2025-01-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0007_remove_spotsnapshot_cft_buoy_data_and_more"),
        ("meteonetwork", "0003_remove_meteonetworkirtdata_spot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meteonetworkirtdata",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="spots.spotsnapshot"
            ),
        ),
    ]
