# Generated by Django 4.2 on 2025-01-04 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spots", "0006_remove_snapshotassessment_wave_type_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPCamLiveWebcam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("alias", models.CharField(max_length=1000, unique=True)),
                ("name", models.CharField(max_length=1000, unique=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="spots.spot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IPCamLiveData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("preview", models.ImageField(upload_to="ipcamlive")),
                (
                    "webcam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ipcamlive.ipcamlivewebcam",
                    ),
                ),
            ],
        ),
    ]
