# Generated by Django 4.2 on 2025-01-04 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0007_remove_spotsnapshot_cft_buoy_data_and_more"),
        ("ipcamlive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipcamlivedata",
            name="snapshot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="spots.spotsnapshot",
            ),
            preserve_default=False,
        ),
    ]
