# Generated by Django 4.2 on 2025-01-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spots", "0003_spot_cft_buoy_station_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CFTBuoyStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_uid",
                    models.CharField(
                        choices=[
                            ("TOS25000001", "Boa Gorgona"),
                            ("TOS25000002", "Boa Giannutri"),
                            ("TOS25000003", "Gombo"),
                            ("TOS25000004", "Castiglione Pescaia"),
                        ],
                        max_length=1000,
                        unique=True,
                    ),
                ),
                ("spots", models.ManyToManyField(to="spots.spot")),
            ],
        ),
    ]
