# Generated by Django 4.2 on 2025-01-06 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CFTBuoyStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_uid",
                    models.CharField(
                        choices=[
                            ("TOS25000001", "Boa Gorgona"),
                            ("TOS25000002", "Boa Giannutri"),
                            ("TOS25000003", "Gombo"),
                            ("TOS25000004", "Castiglione Pescaia"),
                        ],
                        max_length=1000,
                        unique=True,
                    ),
                ),
                ("spots", models.ManyToManyField(to="spots.spot")),
            ],
        ),
        migrations.CreateModel(
            name="CFTBuoyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("as_of", models.DateTimeField()),
                ("wave_height", models.JSONField()),
                ("period", models.JSONField()),
                ("direction", models.JSONField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spots.spotsnapshot",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cftoscana.cftbuoystation",
                    ),
                ),
            ],
        ),
    ]
