# Generated by Django 4.2 on 2025-01-02 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cftoscana", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CFTBuoyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("as_of", models.DateTimeField()),
                ("data", models.JSONField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cftoscana.cftbuoystation",
                    ),
                ),
            ],
        ),
    ]
