# Generated by Django 4.2 on 2025-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cftoscana", "0002_cftbuoydata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cftbuoydata",
            old_name="data",
            new_name="direction",
        ),
        migrations.AddField(
            model_name="cftbuoydata",
            name="period",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cftbuoydata",
            name="wave_height",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
