# Generated by Django 4.2 on 2025-01-04 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0007_remove_spotsnapshot_cft_buoy_data_and_more"),
        (
            "cftoscana",
            "0003_rename_data_cftbuoydata_direction_cftbuoydata_period_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cftbuoydata",
            name="snapshot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="spots.spotsnapshot",
            ),
            preserve_default=False,
        ),
    ]
