# Generated by Django 4.2 on 2025-01-06 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindyWebcam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("windy_uid", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=1000, unique=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="spots.spot"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WindyWebcamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=1000)),
                ("view_count", models.IntegerField()),
                ("status", models.CharField(max_length=1000)),
                ("last_updated_on", models.CharField(max_length=1000)),
                ("preview", models.ImageField(upload_to="windy_webcams")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spots.spotsnapshot",
                    ),
                ),
                (
                    "webcam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="windy.windywebcam",
                    ),
                ),
            ],
        ),
    ]
