# Generated by Django 4.2 on 2024-09-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windywebcamdata",
            name="preview",
            field=models.ImageField(upload_to="windy_webcams"),
        ),
    ]
