# Generated by Django 4.2 on 2025-01-02 20:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("spots", "0005_remove_spot_cft_buoy_station_id_and_more"),
        ("windy", "0002_alter_windywebcamdata_preview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="windywebcamdata",
            name="spot",
        ),
        migrations.AlterField(
            model_name="windywebcamdata",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 20, 8, 18, 143364, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="WindyWebcam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 1, 2, 20, 8, 18, 142993, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("windy_uid", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=1000, unique=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="spots.spot"
                    ),
                ),
            ],
        ),
    ]
