# Generated by Django 4.2 on 2025-01-02 20:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("windy", "0003_remove_windywebcamdata_spot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="windywebcamdata",
            name="windy_webcam_id",
        ),
        migrations.AddField(
            model_name="windywebcamdata",
            name="webcam",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="windy.windywebcam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="windywebcam",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 20, 15, 2, 95944, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="windywebcamdata",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 20, 15, 2, 96331, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
