# Generated by Django 4.2 on 2025-01-02 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("windy", "0006_alter_windywebcam_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windywebcam",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 22, 17, 1, 515055, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="windywebcamdata",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 2, 22, 17, 1, 515438, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
