# Generated by Django 4.2 on 2025-01-03 18:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("windy", "0007_alter_windywebcam_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windywebcam",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="windywebcamdata",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 1, 3, 18, 52, 17, 113834, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
