# Generated by Django 4.2 on 2025-01-03 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("windy", "0008_alter_windywebcam_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="windywebcamdata",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
